### ISSUE TITLE
New-HPOVUplinkSet on Synergy cannot validate uri

### ISSUE THREAD

**Issue by simat90** [HewlettPackard/POSH-HPOneView#289]
Please fill in as much information as possible to help resolve your issue.

### Expected Behavior
To create a new uplinkset to an existing Logical Interconnect.

### Actual Behavior
It seems like the rest call is trying to get "Bay" where in Synergy it maybe should be "interconnect"? I also tried to write interconnect instead of Bay in the -UplinkPorts. I've pasted the verbose output here:

```Powershell
PS C:\> Get-HPOVLogicalInterconnect -Name "Logical Enclosure 1-LIG LAN" | New-HPOVUplinkSet -Name "Test-uplink" -Type Ethernet -Networks "VLAN 10-A" -UplinkPorts "Enclosure1:Bay3:Q2.1" -EthMode "Auto" -verbose
VERBOSE: [NEW-HPOVUPLINKSET] Bound PS Parameters:
Key         Value
---         -----
Name        Test-uplink
Type        Ethernet
Networks    {VLAN 10-A}
UplinkPorts {Enclosure1:Bay3:Q2.1}
EthMode     Auto
Verbose     True


VERBOSE: [NEW-HPOVUPLINKSET] Called from: <ScriptBlock>
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource Name: Logical Enclosure 1-LIG LAN
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource Category: logical-interconnects
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource URI: /rest/logical-interconnects/4457a121-dae1-425d-8fd0-9e001a122262
VERBOSE: [NEWOBJECT] Bound PS Parameters:
Key               Value
---               -----
LiUplinkSetObject True


VERBOSE: [NEWOBJECT] Called from: New-HPOVUplinkSet
VERBOSE: [NEW-HPOVUPLINKSET] Uplink Ports to Process: Enclosure1:Bay3:Q2.1
[NEW-HPOVUPLINKSET] Port configuration is Synergy Ethernet
[NEW-HPOVUPLINKSET] Processing Frame "/rest/enclosures/013645CN759000CA", Bay "3", Port "Q2.1"
VERBOSE: [NEW-HPOVUPLINKSET] Looking for Interconnect URI for Bay 3
New-HPOVUplinkSet : Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
At line:1 char:67
+ ... -LIG LAN" | New-HPOVUplinkSet -Name "Test-uplink" -Type Ethernet -Net ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-HPOVUplinkSet], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-HPOVUplinkSet
```
### Steps to reproduce
With a Synergy trying to add a new uplinkset with New-HPOVUplinkSet

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.10.1416.3042
HPE OneView Appliance Version:  3.10.04-0299553
Output from `$PSVersionTable` on your Windows Host:
```PowerShell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1532
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1532
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
I will need more information on the error you are seeing.  Can you please provide the output from `$error[0] | fl *` and `$error[1] | fl *`.

**Comment by simat90** [comment]
Sure thing:
```
PS C:\> $error[0] | fl *


PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'uri'. -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try
                         again. ---> System.Management.Automation.RuntimeException: -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again. ---> System.Management.Automation.RuntimeEx
                        ception: -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavio
                        r errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationIn
                        fo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
                           at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Send-HPOVRequest], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationError,Send-HPOVRequest
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-HPOVUplinkSet<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1: line 66006
                        at Get-HPOVLogicalInterconnect<End>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1: line 58627
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

```
PS C:\> $error[1] | fl *


PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
TargetObject          : -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
CategoryInfo          : OperationStopped: (-URI must being... and try again.:String) [], RuntimeException
FullyQualifiedErrorId : -URI must being with a '/' (eg. /rest/server-hardware) in its value. Please correct the value and try again.
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1: line 4213
                        at New-HPOVUplinkSet<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1: line 66006
                        at Get-HPOVLogicalInterconnect<End>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.310\HPOneView.310.psm1: line 58627
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Output from Get-HPOVCommandTrace attached:
[1709200858_HPOV_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/1316854/1709200858_HPOV_transcript.txt)

**Comment by ChrisLynchHPE** [comment]
I found the issue.  I have a mistake in processing the interconnect bay mapping of the provided Logical Interconnect.  I'll have the fix released in the next update.

**Comment by simat90** [comment]
Perfect - Thank you for the quick response and thank you for your work. Looking forward to the next update.

**Comment by ChrisLynchHPE** [comment]
I hope to have the update release by next week.  My lab which hosts the infrastructure to perform the CI testing is currently still down.

**Comment by ChrisLynchHPE** [comment]
This is now fixed in [Release 3.10.1471.1581](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1471.1581), which has also been published to the [PowerShellGallery](https://www.powershellgallery.com/packages/HPOneView.310).

**Comment by simat90** [comment]
Thanks for making the update.
Now I'm encountering a new error as seen below:
```
PS C:\> Get-HPOVLogicalInterconnect -Name "Logical Enclosure 1-LIG LAN" | New-HPOVUplinkSet -Name "Test-uplink" -Type Ethernet -Networks "VLAN 10-A" -UplinkPorts "Enclosure1:Bay3:Q2.1" -EthMode "Auto" -verbose
VERBOSE: [NEW-HPOVUPLINKSET] Bound PS Parameters:
Key         Value
---         -----
Name        Test-uplink
Type        Ethernet
Networks    {VLAN 10-A}
UplinkPorts {Enclosure1:Bay3:Q2.1}
EthMode     Auto
Verbose     True


VERBOSE: [NEW-HPOVUPLINKSET] Called from: <ScriptBlock>
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource Name: Logical Enclosure 1-LIG LAN
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource Category: logical-interconnects
VERBOSE: [NEW-HPOVUPLINKSET] Provided LI Resource URI: /rest/logical-interconnects/4457a121-dae1-425d-8fd0-9e001a122262
VERBOSE: [NEWOBJECT] Bound PS Parameters:
Key               Value
---               -----
LiUplinkSetObject True


VERBOSE: [NEWOBJECT] Called from: New-HPOVUplinkSet
VERBOSE: [NEW-HPOVUPLINKSET] Uplink Ports to Process: Enclosure1:Bay3:Q2.1
VERBOSE: [NEW-HPOVUPLINKSET] Port configuration is Synergy Ethernet
VERBOSE: [NEW-HPOVUPLINKSET] Processing Frame "/rest/enclosures/013645CN759000CA", Bay "3", Port "Q2.1"
VERBOSE: [NEW-HPOVUPLINKSET] Looking for Interconnect URI for Bay 3
VERBOSE: [NEW-ERRORRECORD] Building ErrorRecord object
New-HPOVUplinkSet : The Interconnect Bay ID 3 could not be identified within the provided Logical Interconnect resource object.
At line:1 char:67
+ ... -LIG LAN" | New-HPOVUplinkSet -Name "Test-uplink" -Type Ethernet -Net ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (InputObject:String) [New-HPOVUplinkSet], UplinkSetResourceException
    + FullyQualifiedErrorId : UnsupportedLogicalInterconnectResource,New-HPOVUplinkSet
```

If needed I've attached the output from the Get-HPOVCommandTrace:
[1710120916_HPOV_transcript.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/1378435/1710120916_HPOV_transcript.txt)

This is strange because I'm 100% sure that the interconnect 3 is part of this Logical Interconnect.

**Comment by ChrisLynchHPE** [comment]
Please provide the captured file from the following command:

Send-HPOVRequest /rest/logical-interconnects/4457a121-dae1-425d-8fd0-9e001a122262 | ConvertTo-Json -Depth 99 > C:\temp\li.json

**Comment by simat90** [comment]
Sure, here you go in a zip, as Github doesn't support json files:

[li.zip](https://github.com/HewlettPackard/POSH-HPOneView/files/1381926/li.zip)

**Comment by ChrisLynchHPE** [comment]
Thanks.  Yes, your LI does have a Bay 3 Interconnect device.  The Cmdlet should have been finding the resource correctly, and it appears to not be.  I’ll need to look at this further.

**Comment by ChrisLynchHPE** [comment]
Sorry for the extremely late reply.  The [3.10.1560.1882](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v3.10.1560.1882) release should fix your issue finally.  Can you please help confirm?

**Comment by simat90** [comment]
Hi Chris.
No worries about that. 

It seems like I'm getting the same error still after the update. However I've made a workaround by updating the LIG instead. Then I can update the Logical Interconnect from the group and it works out in the end... So don't worry about it.
