### ISSUE TITLE
Error when Invoke-WebRequest / Invoke-RESTMethod against iLO REST API after Connect-HPOVMgmt

### ISSUE THREAD

**Issue by mitsumaui** [HewlettPackard/POSH-HPOneView#327]
Looks like there there is some changes to the .NET SSL management after connecting to OneView, then invoking against an iLO REST endpoint. 

### Expected Behavior

Invoke-WebRequest returns JSON output from iLO REST API call

### Actual Behavior
```PowerShell
PS J:\> $uri = 'https://123.123.123.123/redfish/v1/AccountService/Accounts/'
PS J:\> try { Invoke-WebRequest -Uri $uri -Headers @{'X-AuthToken'='5a91a89230f31331453c77257eb7ba8f'} -Method Get -ContentType 'application/json' } catch { $_.exception | fl * }


StatusCode        : 200
StatusDescription : OK
Content           : {"@odata.context":"/redfish/v1/$metadata#ManagerAccountCollection.ManagerAccountCollection","@odata
                    .etag":"W/\"xxxxx\"","@odata.id":"/redfish/v1/AccountService/Accounts/","@odata.type":"#ManagerA
                    cc...
RawContent        : HTTP/1.1 200 OK
                    Allow: GET, HEAD, POST
                    Link: </redfish/v1/SchemaStore/en/ManagerAccountCollection.json/>; rel=describedby
                    OData-Version: 4.0
                    Transfer-Encoding: chunked
                    X-Frame-Options: sameorigin...
Forms             : {}
Headers           : {[Allow, GET, HEAD, POST], [Link, </redfish/v1/SchemaStore/en/ManagerAccountCollection.json/>;
                    rel=describedby], [OData-Version, 4.0], [Transfer-Encoding, chunked]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 439


PS J:\> Connect-HPOVMgmt -Hostname host.name -Credential $cred -AuthLoginDomain 'domain.com'

ConnectionID Name                 UserName AuthLoginDomain Default
------------ ----                 -------- --------------- -------
*SNIP* Data


PS J:\> Get-HPOVServerProfile

Name       Status   Compliance   Template               Server Hardware        Server Hardware Type Enclosure Group Aff
                                                                                                                    ini
                                                                                                                    ty
----       ------   ----------   --------               ---------------        -------------------- --------------- ---
*SNIP* Data   


PS J:\> try { Invoke-WebRequest -Uri $uri -Headers @{'X-AuthToken'='5a91a89230f31331453c77257eb7ba8f'} -Method Get -ContentType 'application/json' } catch { $_.exception | fl * }
The underlying connection was closed: An unexpected error occurred on a send.
PS J:\> try { Invoke-RestMethod -Uri $uri -Headers @{'X-AuthToken'='5a91a89230f31331453c77257eb7ba8f'} -Method Get -ContentType 'application/json' } catch { $_.exception | fl * }
The underlying connection was closed: An unexpected error occurred on a send.
```
### Steps to reproduce

- ConnectHPOVMgmt
- GetHPOViLOSSO
- Invoke-WebRequest as above.

Works fine if clean not connected to HPOVMgmt first. Something in the HPOV Module is manipulating the SSL validation. 

Additional information;
``` PowerShell
InnerException : HPOneView.Library.ApplianceTransportException: The certificate is not trusted due to these X509CertChain flags: PartialChain
                   Please refer to https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags?view=netframework-4.6 for more information.
                    at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
                    at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
```
### Version Information
```PowerShell
host.name                LibraryVersion Path
--------------------                -------------- ----
ApplianceVersion: 4.00.07.330056.00 4.0.1612.2800  C:\Program Files\WindowsPowerShell\Modules\HPOneView.400

# Output from $PSVersionTable

PS J:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2125
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2125
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
Thanks.  This was brought to my attention internally last week with some other internal HPE partners.  I was inadvertently attaching the custom callback validation delegate to the entire `ServerCertificateValidationCallback` property of the `System.Net.ServicePointManager` static class.  I have an update being worked on that will address this.

**Comment by mitsumaui** [comment]
Hey Chris,

Thanks so much for the fast turnaround of this - that is truly awesome support! I just tested this against the latest commit and can confirm now works perfect! Happy for this to be closed out.

**Comment by ChrisLynchHPE** [comment]
Thanks for confirming.  It shouldn't have happened in the first place.  Glad to have it sorted.
