### ISSUE TITLE
Can't get new-HPOVlicense to work

### ISSUE THREAD

**Issue by tknightblc** [HewlettPackard/POSH-HPOneView#55]
I cannot get the new-HPOVlicense to work in 2.00 library. The came command works fine with 1.20 library on same appliance. Please see my simple example below - script path and file name are correct:

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> write $Connection1

ConnectionID Name           UserName      AuthLoginDomain
------------ ----           --------      ---------------
1            192.168.136.60 Administrator LOCAL          

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> write $Scriptpath
C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> new-HPOVlicense -file "$ScriptPath\OVlicenses\NFRlicense-1.txt" -ApplianceConnection $Connection1
Exception calling "ThrowTerminatingError" with "1" argument(s): "Value cannot be null.
Parameter name: errorRecord"
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:44805 char:5
+                 $PSCmdlet.ThrowTerminatingError($errorRecord)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

I am either missing something here are this command is not working properly under 2.00. Again works fine on same appliance with 1.20 removing -ApplianceConnection

**Comment by ChrisLynchHP** [comment]
Can you execute and provide the output from the following:

$error | % { Format-List -InputObject $_ * }

$error | % { $_.ScriptStackTrace }

Then send me the output.  Please do not close out of your PowrShell window after the error has been displayed, otherwise the above command will not provide the stack trace I need.

**Comment by tknightblc** [comment]
Here you go Chris:

PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { Format-List -InputObject $_ * }


PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ThrowTerminatingError" with "1" argument(s): "Value cannot be null.
                        Parameter name: errorRecord" ---> System.ArgumentNullException: Value cannot be null.
                        Parameter name: errorRecord
                           at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
                           at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ArgumentNullException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44805
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}





PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'method'. '@{type=License; key=}' is
                        not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are allowed. ---> System.Management.Automation.RuntimeException: '@{type=License;
                        key=}' is not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are allowed. ---> System.Management.Automation.RuntimeException:
                        '@{type=License; key=}' is not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are allowed.
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope,
                        Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input,
                        Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1
                        variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe,
                        InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
                           at System.Management.Automation.ValidateEnumeratedArgumentsAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter
                        parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : InvalidData: (:) [RestClient], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationError,RestClient
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4555
                        at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44779
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}





PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: '@{type=License; key=}' is not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are
                        allowed.
TargetObject          : '@{type=License; key=}' is not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are allowed.
CategoryInfo          : OperationStopped: ('@{type=License...UT are allowed.:String) [], RuntimeException
FullyQualifiedErrorId : '@{type=License; key=}' is not a valid Method.  Only GET, POST, DELETE, PATCH, or PUT are allowed.
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4225
                        at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4555
                        at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44779
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}





Errors                      :
Message                     : The string is missing the terminator: ".
ErrorRecord                 : The string is missing the terminator: ".
StackTrace                  :    at System.Management.Automation.AutomationEngine.ParseScriptBlock(String script, String fileName, Boolean interactiveCommand)
                                 at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandFactory
                              commandFactory, Boolean addToHistory, CommandOrigin origin)
                                 at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
WasThrownFromThrowStatement : False
Data                        : {}
InnerException              :
TargetSite                  : System.Management.Automation.ScriptBlock ParseScriptBlock(System.String, System.String, Boolean)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087





Errors                      :
Message                     : The string is missing the terminator: ".
ErrorRecord                 : The string is missing the terminator: ".
StackTrace                  :    at System.Management.Automation.AutomationEngine.ParseScriptBlock(String script, String fileName, Boolean interactiveCommand)
                                 at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandFactory
                              commandFactory, Boolean addToHistory, CommandOrigin origin)
                                 at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
WasThrownFromThrowStatement : False
Data                        : {}
InnerException              :
TargetSite                  : System.Management.Automation.ScriptBlock ParseScriptBlock(System.String, System.String, Boolean)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087



PS C:\Users\tknight\Desktop\OneView\HP OV 2.0 DCS\Toms PS scripts - 2.0 working copy> $error | % { $_.ScriptStackTrace }
at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44805
at <ScriptBlock>, <No file>: line 1
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4555
at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44779
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4225
at Send-HPOVRequest<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 4555
at New-HPOVLicense<Process>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1: line 44779
at <ScriptBlock>, <No file>: line 1

**Comment by ChrisLynchHP** [comment]
I see the problem, and one other inadvertent issue.  Not sure why, but when we send the call to add the license key, we are missing a key parameter for the API call.  It looks like a code merge caused this issue.  I have it fixed for the next library release.

**Comment by tknightblc** [comment]
Chris,

OK thanks, feel better knowing it was not me ;-)

I have a full set of scripts I put together for 1.20 that build out the DCS appliance from scratch. Great demo for customers. I will work around this one and try the other scripts, need to convert my server profile builds to use the new template commands.

I will let you know it GitHub if I find anything else.

                                                                                                                Thanks, Tom Knight

**Comment by ChrisLynchHP** [comment]
NP.  Thanks for reporting it.

**Comment by ChrisLynchHP** [comment]
This is fixed in the upcoming 2.0.139.0 release.
